name: compile latex document
on:
  push:
    paths: [**.tex']
  pull_request:
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        id: latex
        with:
          root_file: src/main.tex
          post_compile: "mkdir build && cp main.pdf build"
          continue_on_error: true
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        id: upload
        with:
          name: PDF
          path: src/main.pdf
        if: always()
        
      - name: Deploy PDF
        uses: JamesIves/github-pages-deploy-action@v4
        id: pages
        with:
          branch: pdf
          folder: src/build

      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        id: release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest"
          files: |
            src/main.pdf
            
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build_pdf

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
